BibliotecaMVC/src/BibliotecaMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Sistema para aluguel de livros";
            ViewData["NomeAluno"] = "Carla Frascareli";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Contato da aluna";
            ViewData["NomeAluno"] = "Carla Frascareli";
            ViewData["EmailAluno"] = "carlafrascareli@gmail.com";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

BibliotecaMVC/src/BibliotecaMVC/ViewComponents/ListagemLivrosViewComponent.cs
using BibliotecaMVC.Data;
using BibliotecaMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaMVC.ViewComponents
{
    public class ListagemLivrosViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public ListagemLivrosViewComponent(ApplicationDbContext c)
        {
            _context = c;
        }

        public async Task<IViewComponentResult> InvokeAsync(int autorID)
        {
            var produtos = await GetListagemLivrosAsync(autorID);
            return View(produtos);
        }

        private Task<IEnumerable<Livro>> GetListagemLivrosAsync(int autorID)
        {
            var livros = _context.Livro.AsNoTracking()
                        .Include(l => l.LivroAutor)
                        .ThenInclude(li => li.Autor)
                        .OrderBy(l => l.Titulo);

            if (autorID != 0)
                livros.Where(x => x.LivroAutor.Any(y => y.AutorID == autorID));

            return Task.FromResult(livros.AsEnumerable());
        }
    }
}

BibliotecaMVC/src/BibliotecaMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre o sistema";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<h3>Aluna:</h3>
<p>@ViewData["NomeAluno"]</p>

BibliotecaMVC/src/BibliotecaMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contato";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["NomeAluno"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>E-mail:</strong> <a href="mailto:@ViewData["EmailAluno"]">@ViewData["EmailAluno"]</a>
</address>

BibliotecaMVC/src/BibliotecaMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}
<h1>Livros em destaque</h1>
<p class="lead">Verifique os livros da nossa Biblioteca abaixo.</p>
<div>
    @await Component.InvokeAsync("ListagemLivros", "")
</div>